### ISSUE TITLE
modal is not responsive

### ISSUE THREAD

**Issue by ymc-crow** [tosspayments/browser-sdk#13]
modal is not responsive in pc browser.

If toss payments modal is shown on new window(using window.open method) that size is under 650 x 650.
then modal looks cut.

although i can resize new window using "window.resizeTo method", but i think it looks good to be dealt with in the toss payments module

**Comment by HyunSeob** [comment]
Hello, @ymc-crow

Sorry, we don't offer a responsive window. but there have been no critical issue by this problem although we have been serving only the fixed-size payment window for years.

Also, this problem is not originated from the SDK. So I would like to recomment that you request to our official technical support channel, techsupport@tosspayments.com. You can get a support more quickly.
